export const URL_SETTINGS_RESPONSE_SUCCESS = "URL_SETTINGS_RESPONSE_SUCCESS"
export const URL_SETTINGS_RESPONSE_FAILURE = "URL_SETTINGS_RESPONSE_FAILURE"

export const URL_SETTINGS_GENERAL_SUCCESS = "URL_SETTINGS_GENERAL_SUCCESS"
export const URL_SETTINGS_GENERAL_FAILURE = "URL_SETTINGS_GENERAL_FAILURE"

export const URL_SETTINGS_CLEAR = "URL_SETTINGS_CLEAR"
