export default {
	URL_LIST_SUCCESS: "URL_LIST_SUCCESS",
	URL_LIST_FAILURE: "URL_LIST_FAILURE",
	DISABLE_URL_SECCESS: "DISABLE_URL_SECCESS",
	DISABLE_URL_FAILURE: "DISABLE_URL_FAILURE",
	ENABLE_URL_SECCESS: "ENABLE_URL_SECCESS",
	ENABLE_URL_FAILURE: "ENABLE_URL_FAILURE"
}